[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
PYTHON_VERSION = "3.11"

[deploy.env]
CLINIKO_API_KEY = "your_api_key_here"
HOST = "0.0.0.0"
PORT = "8000"
